services:
  cockpit:
    image: quay.io/cockpit/ws:latest
    container_name: cockpit
    privileged: true
    pid: host
    networks:
      - shared-web
    volumes:
      - /:/host
    command: ["/container/label-run", "--no-tls", "--port", "9090"]
    restart: unless-stopped

networks:
  shared-web:
    external: true
