version: '3.8'

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    volumes:
      - ./AdGuardHome.yaml:/opt/adguardhome/conf/AdGuardHome.yaml:ro
      - ./work:/opt/adguardhome/work
    networks:
      - lsio
    environment:
      - TZ=Asia/Jakarta

networks:
  lsio:
    external: true